name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Debug - List Project Root
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Package.json content:"
          cat package.json
          
      - name: Build
        env:
          NEXT_PUBLIC_PROJECTS_PASSWORD: ${{ secrets.NEXT_PUBLIC_PROJECTS_PASSWORD }}
          NEXT_PUBLIC_MAINTENANCE_PASSWORD: ${{ secrets.NEXT_PUBLIC_MAINTENANCE_PASSWORD }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: npm run build

      - name: Debug - Check Build Output
        run: |
          echo "Checking if 'out' directory exists:"
          ls -la
          echo "Contents of 'out' directory (if it exists):"
          ls -la out || echo "out directory not found"
          echo "Current working directory:"
          pwd
          
      - name: Configure Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out
          
      - name: Debug - Post Upload
        run: |
          echo "Checking workspace after upload:"
          ls -la
          echo "Environment variables (safe ones only):"
          env | grep -v -i "secret\|key\|password\|token"
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3